version: "3.1"
services:
  chrome:
    image: selenium/standalone-chrome:3.141
    container_name: chrome
    ports:
      - "4444:5555"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
      - SCREEN_WIDTH=1536
      - SCREEN_HEIGHT=864
    expose:
      - 4444
  testing:
    build: .
    command: npm run test:docker
    depends_on:
      - chrome
    volumes:
     - ./reports:/reports
  smoke:
    build: .
    command: npm run test:smoke
    depends_on:
      - chrome
    volumes:
      - ./reports:/reports
  regression:
    build: .
    command: npm run test:regression
    depends_on:
      - chrome
    volumes:
      - ./reports:/reports
