export const BASE_URL = 'https://...'
export const LOGIN = 'auth/login'
export const LOGOUT = 'auth/logout'
export const HTTP_GET = 'GET'
export const HTTP_POST = 'POST'
export const HTTP_PUT = 'PUT'
export const HTTP_DELETE = 'DELETE'
export const HTTP_PATCH = 'PATCH'