name: Automated Suite Execution
on:
  repository_dispatch:
   types: test-on-demand
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        if: github.event.action == 'test-on-demand' # any event name can be used here
        run: |
         echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.github_repository }}'*${{ github.event.client_payload.github_ref }}@'${{ github.event.client_payload.github_sha }}'. Sent by: '${{ github.event.client_payload.github_actor}}'"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
         node-version: '12.0.0'
      - name: Testing Web App On Demand
        if: github.event.action == 'test-on-demand'
        id: demanded
        run: ./e2e-daily-execution-script-on-demand.sh
        timeout-minutes: 60
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: general-report
          path: ./reports/html-reports/tests-results.html
      - name: Send to Slack
        if: success()
        run: |
            curl -X POST ${{ secrets.SLACK_WEBHOOK_URL}} -H "Content-type: application/json" --data '{
                                                                                                 	"blocks": [
                                                                                                 		{
                                                                                                 			"type": "divider"
                                                                                                 		},
                                                                                                 		{
                                                                                                 			"type": "section",
                                                                                                 			"text": {
                                                                                                 				"type": "mrkdwn",
                                                                                                 				"text": "*Farmhouse Thai Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"
                                                                                                 			},
                                                                                                 			"accessory": {
                                                                                                 				"type": "image",
                                                                                                 				"image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg",
                                                                                                 				"alt_text": "alt text for image"
                                                                                                 			}
                                                                                                 		},
                                                                                                 		{
                                                                                                 			"type": "divider"
                                                                                                 		}
                                                                                                 	]
                                                                                                 }'
