name: Trigger Tests for Dependencies PRs
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Conditions
        if: |
          (github.event.action == 'labeled' &&
          github.event.label.name == 'expectedLabel' )
        run: |
          echo "Pull request was labeled with ${{ github.event.label.name }}. This action will trigger the tests execution"
      - name: Start E2E Tests
        if: |
          (github.event.action == 'labeled' &&
          github.event.label.name == 'expectedLabel' )
        run: ./e2e-daily-execution-script-scheduled.sh
      - uses: actions/upload-artifact@v2  
        if: success()
        with:
          name: general-report
          path: ./reports/html-reports/tests-results.html
      - name: Send to Slack
        if: success()
        run: |
              curl -X POST ${{ secrets.SLACK_WEBHOOK_URL}} -H "Content-type: application/json" --data '{
                                                                                               	"blocks": [
                                                                                               		{
                                                                                               			"type": "divider"
                                                                                               		},
                                                                                               		{
                                                                                               			"type": "divider"
                                                                                               		},
                                                                                               		{
                                                                                               			"type": "section",
                                                                                               			"text": {
                                                                                               				"type": "mrkdwn",
                                                                                               				"text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                                                                                               			}
                                                                                               		}
                                                                                               	]
                                                                                               }'
