name: Manual triggering
on:
  workflow_dispatch:
   inputs:
    base_url:
       description: 'base Url'
       required: true
    parameter_1:
     description: 'First Required Parameter'
     required: true
    parameter_2:
      description: 'Second Parameter'
      required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cheking if request was made manually
        if: github.event_name == 'workflow_dispatch'
        run: |
         echo "Execution Manually Triggered"
         echo "The provided parameters were ${{github.event.inputs.parameter_1}} && ${{github.event.inputs.parameter_2}}"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
         node-version: '12.16.1'
      - name: Getting Workflow Run Data
        if: success()
        id: runid
        uses: actions/github-script@0.8.0
        with:
          script: |
            const wf_run = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }}
            })
            console.log(wf_run.data)
            const jobs_response = await github.request(wf_run.data.jobs_url)

            let runLink = wf_run.data.html_url

            return wf_run.data.html_url
      - name: Launching Execution
        id: dependencies
        run: ./e2e-daily-execution-script.sh baseurl=${{ github.event.inputs.base_url }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
         name: general-report
         path: |
          ./reports/html-reports/tests-results.html
          ./reports/html-reports/report-styles.css
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: before-suite-screenshots
          path: ./reports/html-reports/screenshots/bs-*.png
          if-no-files-found: ignore # 'warn' or 'ignore' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: partial-reports
          path: ./reports/html-reports/screenshots/
      - name: Sending Results to Slack Channel
        if: success()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL}} -H "Content-type: application/json" --data '${{ steps.status.outputs.result }}'