name: Automated Suite Execution
on:
  #schedule:
   #- cron: "0 */8 * * 1-5"
  # Uncomment line 3 and line 5, and comment line 6 and line 7 to set schedule workflows 
  repository_dispatch:
   types: test-on-demand
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        if: github.event_name == 'schedule'
        run: |
          echo "Schedule Execution was Launched"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
         node-version: '12.0.0'
      - name: Testing Web App Scheduled Execution
        if: github.event_name == 'schedule'
        id: scheduled
        run: ./e2e-daily-execution-script-on-demand.sh
        timeout-minutes: 120
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: general-report
          path: ./reports/html-reports/tests-results.html
      - name: Send to Slack
        if: success()
        run: |
            curl -X POST ${{ secrets.SLACK_WEBHOOK_URL}} -H "Content-type: application/json" --data '{
                                                                                                 	"blocks": [
                                                                                                 		{
                                                                                                 			"type": "divider"
                                                                                                 		},
                                                                                                 		{
                                                                                                 			"type": "divider"
                                                                                                 		},
                                                                                                 		{
                                                                                                 			"type": "section",
                                                                                                 			"text": {
                                                                                                 				"type": "plain_text",
                                                                                                 				"text": "This is a plain text section block.",
                                                                                                 				"emoji": true
                                                                                                 			}
                                                                                                 		},
                                                                                                 		{
                                                                                                 			"type": "section",
                                                                                                 			"text": {
                                                                                                 				"type": "mrkdwn",
                                                                                                 				"text": "Test block with users select"
                                                                                                 			},
                                                                                                 			"accessory": {
                                                                                                 				"type": "users_select",
                                                                                                 				"placeholder": {
                                                                                                 					"type": "plain_text",
                                                                                                 					"text": "Select a user",
                                                                                                 					"emoji": true
                                                                                                 				},
                                                                                                 				"action_id": "users_select-action"
                                                                                                 			}
                                                                                                 		}
                                                                                                 	]
                                                                                                 }'
